### ISSUE TITLE
Errors downloading USS file

### ISSUE THREAD

**Issue by plavjanik** [zowe/zowe-cli-ftp-plugin#96]
I am trying to download a USS file with the following command:

```sh
zowe zftp dl uss /a/myhome/sca.jar -f sca.jar --binary --zftp-profile mysystem
```

It fails with the following error:
```
TypeError: Cannot read properties of undefined (reading 'indexOf')
    at /Users/plape03/.zowe/plugins/installed/lib/node_modules/@zowe/zos-ftp-for-zowe-cli/node_modules/zos-node-accessor/lib/zosAccessor.js:326:23
    at Array.forEach (<anonymous>)
    at ZosAccessor.parseUSSDirList (/Users/plape03/.zowe/plugins/installed/lib/node_modules/@zowe/zos-ftp-for-zowe-cli/node_modules/zos-node-accessor/lib/zosAccessor.js:316:13)
    at /Users/plape03/.zowe/plugins/installed/lib/node_modules/@zowe/zos-ftp-for-zowe-cli/node_modules/zos-node-accessor/lib/zosAccessor.js:292:47
    at final (/Users/plape03/.zowe/plugins/installed/lib/node_modules/@zowe/zos-ftp-for-zowe-cli/node_modules/ftp4/lib/connection.js:487:11)
    at Object.cb (/Users/plape03/.zowe/plugins/installed/lib/node_modules/@zowe/zos-ftp-for-zowe-cli/node_modules/ftp4/lib/connection.js:524:11)
    at Parser.<anonymous> (/Users/plape03/.zowe/plugins/installed/lib/node_modules/@zowe/zos-ftp-for-zowe-cli/node_modules/ftp4/lib/connection.js:120:20)
    at Parser.emit (node:events:390:28)
    at Parser._write (/Users/plape03/.zowe/plugins/installed/lib/node_modules/@zowe/zos-ftp-for-zowe-cli/node_modules/ftp4/lib/parser.js:59:10)
    at writeOrBuffer (node:internal/streams/writable:389:12)
Command Error:
Cannot read properties of undefined (reading 'indexOf')
Imperative encountered an unexpected exception
Command entered: "zowe zftp dl uss /a/plape03/sca.jar -f sca.jar --binary --zftp-profile ca32-plape03"
Use "zowe zftp dl --help" to view groups, commands, and options.
Error Details:
Cannot read properties of undefined (reading 'indexOf')
```

What I am doing wrong. The command syntax seems correct and the file exists.

I tried to download it from a different location and it failed a different way:

```sh
zowe zftp dl uss /tmp/sca.jar -f sca.jar --binary --zftp-profile mysystem
```

Error message:
```
Command Error:
Unrecognized file list header: lrwxrwxrwx   1 STCSYS   OMVSGRP       12 Jan 21  2010 /tmp -> $SYSNAME/tmp
```

**Comment by std4lqi** [comment]
Hi @plavjanik, any FTP output you could share?

**Comment by plavjanik** [comment]
Yes. I have lost the original files when I was migrating the filesystem. But I was able to reproduce it.

I have created a directory `/a/USERID /test/special_character` and run the following script in it:
https://gist.github.com/plavjanik/803c98271e9f9cb574580a14a8ad2d5f

It creates 255 files, each with a different special character.

Downloading a file from this directory displays the same error message and gets stuck:
```
zowe zftp dl uss /a/USERID /test/special_character/s.sh -f s.sh --binary
TypeError: Cannot read properties of undefined (reading 'indexOf')
    at /Users/USERID /.zowe/plugins/installed/lib/node_modules/@zowe/zos-ftp-for-zowe-cli/node_modules/zos-node-accessor/lib/zosAccessor.js:326:23
    at Array.forEach (<anonymous>)
    at ZosAccessor.parseUSSDirList (/Users/USERID /.zowe/plugins/installed/lib/node_modules/@zowe/zos-ftp-for-zowe-cli/node_modules/zos-node-accessor/lib/zosAccessor.js:316:13)
    at /Users/USERID /.zowe/plugins/installed/lib/node_modules/@zowe/zos-ftp-for-zowe-cli/node_modules/zos-node-accessor/lib/zosAccessor.js:292:47
    at final (/Users/USERID /.zowe/plugins/installed/lib/node_modules/@zowe/zos-ftp-for-zowe-cli/node_modules/ftp4/lib/connection.js:487:11)
    at Object.cb (/Users/USERID /.zowe/plugins/installed/lib/node_modules/@zowe/zos-ftp-for-zowe-cli/node_modules/ftp4/lib/connection.js:524:11)
    at Parser.<anonymous> (/Users/USERID /.zowe/plugins/installed/lib/node_modules/@zowe/zos-ftp-for-zowe-cli/node_modules/ftp4/lib/connection.js:120:20)
    at Parser.emit (node:events:390:28)
    at Parser._write (/Users/USERID /.zowe/plugins/installed/lib/node_modules/@zowe/zos-ftp-for-zowe-cli/node_modules/ftp4/lib/parser.js:59:10)
    at writeOrBuffer (node:internal/streams/writable:389:12)
Command Error:
Cannot read properties of undefined (reading 'indexOf')
Imperative encountered an unexpected exception
Command entered: "zowe zftp dl uss /a/USERID /test/invalid_character/s.sh -f s.sh --binary --zftp-profile ca32"
Use "zowe zftp dl --help" to view groups, commands, and options.
Error Details:
Cannot read properties of undefined (reading 'indexOf')
```

The FTP dir output is:
```
Command:
dir
>>> PORT 127,0,0,1,165,69
200 Port request OK.
>>> LIST
125 List started OK
total 32
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:37 Invalid character 001  END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:37 Invalid character 002  END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:37 Invalid character 003  END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:37 Invalid character 004  END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:37 Invalid character 005 	 END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:37 Invalid character 006  END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:37 Invalid character 007  END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:37 Invalid character 008
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:37 Invalid character 009
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:37 Invalid character 010  END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:37 Invalid character 011  END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:37 Invalid character 012  END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:37 Invalid character 013
                                                                             END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:37 Invalid character 014
                                                                             END
 ENDr--r--   1 USERID   GROUP          0 Nov  4 12:37 Invalid character 015
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:37 Invalid character 016  END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:37 Invalid character 017  END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:37 Invalid character 018 8 END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:37 Invalid character 019 9 END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:37 Invalid character 020  END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:37 Invalid character 021  END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:37 Invalid character 022  END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:37 Invalid character 023  END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:37 Invalid character 024  END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:37 Invalid character 025
 END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:37 Invalid character 026 END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:37 Invalid character 027  END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:37 Invalid character 028 8 END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:37 Invalid character 029 9 END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:37 Invalid character 030  END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:37 Invalid character 031  END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:37 Invalid character 032  END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:37 Invalid character 033  END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:37 Invalid character 034 � END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:37 Invalid character 035  END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:37 Invalid character 036 � END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:37 Invalid character 037  END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:37 Invalid character 038 8 END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:37 Invalid character 039 9 END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 040  END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 041  END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 042 � END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 043  END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 044  END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 045 � END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 046  END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 047  END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 048 8 END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 049 9 END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 050  END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 051  END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 052  END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 053  END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 054  END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 055  END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 056  END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 057  END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 058 	8 END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 059 	9 END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 060  END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 061  END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 062  END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 063  END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 064  END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 065 � END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 066  END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 067  END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 068 8 END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 069 9 END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 070  END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 071  END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 072  END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 073  END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 074  END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 075  END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 076  END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 077  END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 078 8 END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 079 9 END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 080
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 081
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 082
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 083
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 084
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 085
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 086
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 087
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 088
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 089
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 090
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 091
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 092
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 093
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 094
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 095
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 096
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 097
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 098
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 099
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 100 \100 END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 101 \101 END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 102 \102 END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 103 \103 END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 104 \104 END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 105 \105 END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 106 \106 END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 107 \107 END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 108 \108 END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 109 \109 END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 110 \110 END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 111 \111 END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 112 \112 END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 113 \113 END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 114 \114 END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 115 \115 END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 116 \116 END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 117 \117 END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 118 \118 END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 119 \119 END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 120 \120 END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 121 \121 END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 122 \122 END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 123 \123 END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 124 \124 END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 125 \125 END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 126 \126 END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 127 \127 END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 128 \128 END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 129 \129 END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 130 \130 END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 131 \131 END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 132 \132 END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 133 \133 END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 134 \134 END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 135 \135 END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 136 \136 END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 137 \137 END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 138 \138 END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 139 \139 END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 140 \140 END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 141 \141 END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 142 \142 END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 143 \143 END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 144 \144 END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 145 \145 END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 146 \146 END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 147 \147 END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 148 \148 END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 149 \149 END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 150 \150 END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 151 \151 END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 152 \152 END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 153 \153 END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 154 \154 END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 155 \155 END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 156 \156 END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 157 \157 END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 158 \158 END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 159 \159 END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 160 \160 END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 161 \161 END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 162 \162 END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 163 \163 END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 164 \164 END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 165 \165 END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 166 \166 END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 167 \167 END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 168 \168 END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 169 \169 END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 170 \170 END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 171 \171 END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 172 \172 END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 173 \173 END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 174 \174 END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 175 \175 END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 176 \176 END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 177 \177 END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 178 \178 END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 179 \179 END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 180 \180 END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 181 \181 END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 182 \182 END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 183 \183 END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 184 \184 END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 185 \185 END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 186 \186 END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 187 \187 END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 188 \188 END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 189 \189 END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 190 \190 END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 191 \191 END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 192 \192 END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 193 \193 END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 194 \194 END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 195 \195 END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 196 \196 END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 197 \197 END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 198 \198 END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 199 \199 END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 200 \200 END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 201 \201 END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 202 \202 END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 203 \203 END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 204 \204 END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 205 \205 END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 206 \206 END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 207 \207 END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 208 \208 END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 209 \209 END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 210 \210 END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 211 \211 END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 212 \212 END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 213 \213 END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 214 \214 END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 215 \215 END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 216 \216 END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 217 \217 END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 218 \218 END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 219 \219 END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 220 \220 END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 221 \221 END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 222 \222 END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 223 \223 END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 224 \224 END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 225 \225 END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 226 \226 END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 227 \227 END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 228 \228 END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 229 \229 END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 230 \230 END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 231 \231 END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 232 \232 END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 233 \233 END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 234 \234 END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 235 \235 END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 236 \236 END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 237 \237 END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 238 \238 END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 239 \239 END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 240 \240 END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 241 \241 END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 242 \242 END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 243 \243 END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 244 \244 END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 245 \245 END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 246 \246 END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 247 \247 END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 248 \248 END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 249 \249 END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 250 \250 END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 251 \251 END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 252 \252 END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 253 \253 END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 254 \254 END
-rw-r--r--   1 USERID   GROUP          0 Nov  4 12:38 Invalid character 255 \255 END
-rwxrwx--x   1 USERID   GROUP      12240 Nov  4 12:37 s.sh
250 List completed successfully.
```

**Comment by std4lqi** [comment]
Thanks, @plavjanik ! It need be fixed in `zos-node-accessor`. I opened the issue at https://github.com/IBM/zos-node-accessor/issues/69.

**Comment by plavjanik** [comment]
Thank you @std4lqi for finding the root cause and opening the issue.
